---
title: "Case_study_maps"
author: "Serena Verdi"
date: "26/10/2021"
output: html_document
---
Summary: This script creates individual brain maps according demographic, genotypic, cognitive and CSF amyloid critera

Paths to data will need to be changed accordingly.
#-----------------------------------------------
# Setup
#-----------------------------------------------
# Librarys
```{r setup}
library(dplyr)
library(psych)
library(tidyr)
library(readr)
library(ADNIMERGE)
library(data.table)
library(matrixStats)
library(stringr)
library(ggseg)
library(ggsegExtra)
library(ggsegDesterieux)
library(RPMG)
library(cowplot)
```

# Clear workspace
```{r}
rm(list = ls())
```
#Read in data 

```{r}
## Composite Cognitive Score
#df <- read.csv("~/OneDrive - University College London/Chapter 2 cross sectional AD/ADNI_project/Full_study/Results/z_score_stats_cognition/z_scores_cc.csv")


## MMSE z_score_mmse
df <- read.csv("~/OneDrive - University College London/Chapter 2 cross sectional AD/ADNI_project/Full_study/Results/z_score_stats_cognition/z_score_mmse.csv")

## CSF measures
z_csf <- read.csv("~/OneDrive - University College London/Chapter 2 cross sectional AD/ADNI_project/Full_study/Results/z_score_biospec/z_scores_bs.csv")


## APOE status
z_apoe <- read.csv("~/OneDrive - University College London/Chapter 2 cross sectional AD/ADNI_project/Full_study/Results/z_score_biospec/z_scores_apoe.csv")

```
# Prepare data
```{r}
df <- df[-grep("subject_id|.x|X|VISCODE|USER|SCAN|diff|EXAM|date|RUNDATE|VERSION|ORIG|STATUS|LONI|IMAGE|quality",names(df))]

df$gender <- gsub("2", "Female", df$gender)
df$gender <- gsub("1", "Male", df$gender)
df$gender <- factor(df$gender)

# merge z_apoe status with df
z_apoe <-  z_apoe[grep("RID|apoe_status",names(z_apoe))]
df<- merge(df, z_apoe, by= "RID", all.x = TRUE) 

# merge z_csf status with df
z_csf <-  z_csf[grep("RID|ABETA|PTAU",names(z_csf))]
df<- merge(df, z_csf, by= "RID", all.x = TRUE) 

#move cog scores to front
#df <- df %>% relocate(ADNI_MEM)
#df <- df %>% relocate(ADNI_EF)
df <- df %>% relocate(MMSCORE)
df <- df %>% relocate(apoe_status)
df <- df %>% relocate(ABETA)
df <- df %>% relocate(PTAU)

```


#-----------------------------------------------
#Create total outlier score
#-----------------------------------------------
# Thresholding z-scores 

```{r}
# outlier_threshold <- -1.65 ## bottom 5%
outlier_threshold <- -1.96 ## bottom 2.5%
# outlier_threshold <- -2.58 ## bottom 0.05%
```
# Binerising z-scores
```{r}
# z-cc
temp<- as.data.frame(ifelse(df[,12:159] < outlier_threshold,1,0))
temp <- temp %>% rename_all(paste0, "_bin")

df$total_outlier_score <- rowSums(temp)
df <- cbind(df, temp)
```
#-----------------------------------------------
# Filter critera
#-----------------------------------------------
# Group, Age, sex, ADNI_MEM, 
```{r}
# via diagnosis
subset <- df %>% filter(diagnosis == "Dementia") 
#subset <- df %>% filter(diagnosis == "MCI") 


# via sex
subset <- subset %>% filter(gender == "Female")
#subset <- subset %>% filter(gender.y == "Male")


# via apoe
subset <- subset %>% filter(apoe_status == "e4_hetro")


# via average age (+/- 6 months because created approximate dob from MM/YY )
subset <- subset %>% filter(between(age,71,72.99)) 

# via cog score
#subset <- subset %>% filter(between(ADNI_MEM,-2,-1)) 
subset <- subset %>% filter(between(MMSCORE,20,21)) 

subset$RID

## AD_M_aged83-85_MMSCORE20_apoee4hetro = 566 633 5056 5210

##AD_F_aged71_MMSCORE20-21_e4hetro = 814 4373 4657 4696

## MCI_M_aged 69_MMSCORE26_apoe4hetro = 2087 4312 4668 4896

##MCI_F_age_75-78_MMSCORE25_e4hetro = 4294 4909 4909 4929

## AD_F_age70-72_MMSE20andunder_apoe4hetro = 671 4373 4696 6600



```

#-----------------------------------------------
# Individual maps
#-----------------------------------------------
```{r}
f_ggseg <- function(varID) {

  rid_ <- df %>% filter(RID == varID) #edit df here, use subset for subset critera or df for all
  rid_ <- rid_[,grep("_bin",names(rid_))]
  rid_ <- gather(rid_) 
  rid_$ROI <- rid_$key
  rid_$ROI <- gsub("_bin", "", rid_$ROI)
  rid <- rid_
  
# RID 4929
#rid4929 <- df %>% filter(RID == "4929") 
#rid4929 <- rid4929[,grep("_bin",names(rid4929))]
#rid4929 <- gather(rid4929) 
#rid4929$ROI <- rid4929$key
#rid4929$ROI <- gsub("_bin", "", rid4929$ROI)
#rid <- rid4929

#Convert existing data to desterieux atlas
left.rid <- rid %>%
  filter(str_detect(ROI, "L_"))
x <- gsub("L_", "", left.rid$ROI)
y <- gsub("G.S_", "G and S ", x)
z <- gsub("G_", "G ", y)
z1 <- gsub("S_", "S ", z)
z2 <- gsub("_", " ", z1)
z3 <- gsub(" bin", "", z2)
z4 <- gsub("\\.", " ", z3)
z5 <- gsub("cingul ", "cingul-", z4)
z6 <- gsub("Mid ", "Mid-", z5)
z7 <- gsub("Post ", "Post-", z6)
z8 <- gsub("inf ", "inf-", z7)
z9 <- gsub("med ", "med-", z8)
z10 <- gsub("sup ", "sup-", z9)
z11 <- gsub("Fis ant ", "Fis-ant-", z10)
z12 <- gsub("precentral ", "precentral-", z11)
z13 <- gsub("Fis pos ", "Fis-pos-", z12)
z14 <- gsub("lg S", "lg and S", z13)
z15 <- gsub("oc temp", "oc-temp", z14)
z16 <- gsub("sup and transversal", "sup-transversal", z15)
z17 <- gsub("orbital H Shaped", "orbital-H Shaped", z16)
z18 <- gsub("oc sup-transversal", "oc sup and transversal", z17)
z19 <- gsub("prim Jensen", "prim-Jensen", z18)
z20 <- gsub("S oc-temp med-Lingual", "S oc-temp med and Lingual", z19)
z21 <- gsub("lat fusifor", "lat-fusifor", z20)
z22 <- gsub("middle Lunatus", "middle and Lunatus", z21)
z23 <- gsub("intrapariet P trans", "intrapariet and P trans", z22)
renamed_ROIs <- gsub("Lat Fis post", "Lat Fis-post", z23)

desterieux_ROIs <- as.data.frame(desterieux %>% filter(hemi == "left"))$region
compare_lists <- cbind(sort(renamed_ROIs), sort(unique(desterieux_ROIs)))
list_matches <- compare_lists[,1] %in% compare_lists[,2]
compare_lists[!list_matches,]
## if no mismatches, than add to data.frame as region
left.rid$region <- renamed_ROIs

right.rid <- rid %>%
  filter(str_detect(ROI, "R_"))
x <- gsub("R_", "", right.rid$ROI)
y <- gsub("G.S_", "G and S ", x)
z <- gsub("G_", "G ", y)
z1 <- gsub("S_", "S ", z)
z2 <- gsub("_", " ", z1)
z3 <- gsub(" bin", "", z2)
z4 <- gsub("\\.", " ", z3)
z5 <- gsub("cingul ", "cingul-", z4)
z6 <- gsub("Mid ", "Mid-", z5)
z7 <- gsub("Post ", "Post-", z6)
z8 <- gsub("inf ", "inf-", z7)
z9 <- gsub("med ", "med-", z8)
z10 <- gsub("sup ", "sup-", z9)
z11 <- gsub("Fis ant ", "Fis-ant-", z10)
z12 <- gsub("precentral ", "precentral-", z11)
z13 <- gsub("Fis pos ", "Fis-pos-", z12)
z14 <- gsub("lg S", "lg and S", z13)
z15 <- gsub("oc temp", "oc-temp", z14)
z16 <- gsub("sup and transversal", "sup-transversal", z15)
z17 <- gsub("orbital H Shaped", "orbital-H Shaped", z16)
z18 <- gsub("oc sup-transversal", "oc sup and transversal", z17)
z19 <- gsub("prim Jensen", "prim-Jensen", z18)
z20 <- gsub("S oc-temp med-Lingual", "S oc-temp med and Lingual", z19)
z21 <- gsub("lat fusifor", "lat-fusifor", z20)
z22 <- gsub("middle Lunatus", "middle and Lunatus", z21)
z23 <- gsub("intrapariet P trans", "intrapariet and P trans", z22)
renamed_ROIs <- gsub("Lat Fis post", "Lat Fis-post", z23)

desterieux_ROIs <- as.data.frame(desterieux %>% filter(hemi == "right"))$region
compare_lists <- cbind(sort(renamed_ROIs), sort(unique(desterieux_ROIs)))
list_matches <- compare_lists[,1] %in% compare_lists[,2]
compare_lists[!list_matches,]

## if no mismatches, than add to data.frame as region
right.rid$region <- renamed_ROIs

# Plot outliers using ggseg (## add rid number to ggsave to save seperate maps)

                           
left <- ggseg(.data=left.rid, atlas = desterieux, mapping=aes(fill=value), hemisphere = "left", colour = "white", size = 0.2) + 
scale_fill_gradientn(limits = c(0.1,1), colours =  rainbow.colors(5))

right <- ggseg(.data=right.rid, atlas = desterieux, mapping=aes(fill=value), hemisphere = "right", colour = "white", size = 0.2) +
  scale_fill_gradientn(limits = c(0.1,1), colours = rainbow.colors(5))

plot_grid(left,right, nrow = 2, labels = "AUTO")

#ggsave("~/OneDrive - University College London/Chapter 2 cross sectional AD/ADNI_project/Full_study/Results/z_score_stats/RID_4929.pdf")  ##rename!


  ggsave(sprintf("~/OneDrive - University College London/Chapter 2 cross sectional AD/ADNI_project/Full_study/Results/%s.pdf", varID))
}
lapply(unique(df$RID), f_ggseg) #update df here accordingly

```